image: python:3.7-slim

services:
  - redis
  - pip_install
stages:
  - connect redis

connect:
  image: redis
  script:
  - redis-cli -h redis PING
  -
pip_install:
  - python --version
  - pip install -r .requirements.txt --no-cache-dir

#test:
#  tags:
#    - python
#  script:
#    - cd ./src/ && python -m pytest unit_test

